    baseurl = "https://nxxxsooo.github.io"
        languageCode = "en-us"
        theme = "hugo-theme-stack"
        paginate = 3
        title = "Mingjian"
        copyright = "Mingjian Shao"
        DefaultContentLanguage = "en"
        hasCJKLanguage = true

      [languages.en]
        languageName = "English"
        title = "Mingjian"
        weight = 1

      [languages.en.params]
        description = "Mingjian"


      [services.disqus]
        shortname = "hugo-theme-stack"

      [services.googleAnalytics]

      [permalinks]
        post = "/p/:slug/"
        page = "/:slug/"

      [params]
        mainSections = [ "post" ]
        featuredImageField = "image"
        rssFullContent = true

      [params.footer]
        since = 2_024
        customText = "Whenever you feel like criticizing anyone, just remember that all the people in this world haven’t had the advantages that you’ve had."

      [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"

      [params.sidebar]
        emoji = "🍻"
        subtitle = "Don't worry, be happy."

      [params.sidebar.avatar]
        enabled = true
        local = true
        src = "img/avatar.png"

      [params.article]
        math = true
        toc = true
        readingTime = true

      [params.article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

      [params.comments]
        enabled = true
        provider = "disqus"

      [params.comments.disqusjs]

      [params.comments.utterances]
        issueTerm = "pathname"

      [params.comments.beaudar]
        issueTerm = "pathname"

      [params.comments.remark42]

      [params.comments.vssue]
        autoCreateIssue = false

      [params.comments.waline]
        emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
        requiredMeta = [ "name", "email", "url" ]

      [params.comments.waline.locale]
        admin = "Admin"

      [params.comments.twikoo]

      [params.comments.cactus]
        defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
        serverName = "cactus.chat"
        siteName = ""

      [params.comments.giscus]
        reactionsEnabled = 1
        emitMetadata = 0

      [params.comments.gitalk]

      [params.comments.cusdis]

      [[params.widgets.homepage]]
        type = "search"

      [[params.widgets.homepage]]
        type = "archives"

      [params.widgets.homepage.params]
        limit = 5

      [[params.widgets.homepage]]
        type = "categories"

      [params.widgets.homepage.params]
        limit = 10

      [[params.widgets.homepage]]
        type = "tag-cloud"

      [params.widgets.homepage.params]
        limit = 10

      [[params.widgets.page]]
        type = "toc"

      [params.opengraph.twitter]
        card = "summary_large_image"

      [params.defaultImage.opengraph]
        enabled = false
        local = false

      [params.colorScheme]
        toggle = true
        default = "auto"

      [params.imageProcessing.cover]
        enabled = true

      [params.imageProcessing.content]
        enabled = true

      [menu]
        main = [ ]

      [[menu.social]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/noahshao/"

      [menu.social.params]
        icon = "brand-linkedin"

      [[menu.social]]
        identifier = "x"
        name = "X"
        url = "https://x.com/nxxxsooo"

      [menu.social.params]
        icon = "brand-x"

      [related]
        includeNewer = true
        threshold = 60
        toLower = false

      [[related.indices]]
        name = "tags"
        weight = 100

      [[related.indices]]
        name = "categories"
        weight = 200

      [markup.goldmark.renderer]
        unsafe = true

      [markup.tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2

      [markup.highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 4
